export enum CharacterActionTypes {
  SET_IS_LOADING = "CHARACTER/SET_IS_LOADING",
  SET_ERROR = "CHARACTER/SET_ERROR",
  SET_CHARACTERS = "CHARACTER/SET_CHARACTER",
  SET_SINGLE_CHARACTER = "CHARACTER/SET_SINGLE_CHARACTER",
}
