export enum EpisodeActionTypes {
  SET_IS_LOADING = "EPISODE/SET_IS_LOADING",
  SET_ERROR = "EPISODE/SET_ERROR",
  SET_EPISODES = "EPISODE/SET_EPISODE",
  SET_SINGLE_EPISODE = "EPISODE/SET_SINGLE_EPISODE",
}
