export enum LocationActionTypes {
  SET_IS_LOADING = "LOCATION/SET_IS_LOADING",
  SET_ERROR = "LOCATION/SET_ERROR",
  SET_LOCATIONS = "LOCATION/SET_LOCATION",
  SET_SINGLE_LOCATION = "LOCATION/SET_SINGLE_LOCATION",
}
